### ISSUE TITLE
Cannot resolve module 'rxjs/rx'

### ISSUE THREAD

**Issue by olastor** [binarious/meditation-plus-angular#1]
Hi,

After I run `npm run start:hmr` I get following error message (both in Terminal and a similar one in Console/WebBrowser):

`65/102 build modulesError: Cannot resolve module 'rxjs/rx' in /home/sebastian/Dokumente/meditation-plus-angular/src/app/user
    Required in /home/sebastian/Dokumente/meditation-plus-angular/src/app/user/user.service.ts Error: Cannot resolve module 'rxjs/rx' in /home/sebastian/Dokumente/meditation-plus-angular/src/app/user
    Required in /home/sebastian/Dokumente/meditation-plus-angular/src/app/user/user.service.ts
    at ResolutionError.Error (native)
    at new ResolutionError (/home/sebastian/Dokumente/meditation-plus-angular/node_modules/awesome-typescript-loader/dist.babel/deps.js:515:88)
    at /home/sebastian/Dokumente/meditation-plus-angular/node_modules/awesome-typescript-loader/dist.babel/deps.js:340:37
    at run (/home/sebastian/Dokumente/meditation-plus-angular/node_modules/core-js/modules/es6.promise.js:89:22)
    at /home/sebastian/Dokumente/meditation-plus-angular/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/home/sebastian/Dokumente/meditation-plus-angular/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by binarious** [comment]
Hi,

we should keep this in english so others could benefit from it if you're okay with it.

We're there any errors during `npm install`? If you're unsure you could remove the `node_modules` folder and run the command again. What's the output of `tsc --diagnostics` in the root folder of the project?

**Comment by olastor** [comment]
I get these errors during `npm install`

`node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-linux-x64.tar.gz`
`node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.2.2 (node-v48 ABI) (falling back to source compile with node-gyp) `

and these warnings

`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`
`npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`
`npm WARN prefer global marked@0.3.5 should be installed with -g`
...
`typings WARN deprecated 6/6/2016, 6:18:17 PM: "registry:npm/moment#2.10.5+20160211003958" has been deprecated`
`typings WARN deprecated 6/23/2016, 1:36:04 AM: "registry:dt/hammerjs#2.0.4+20160417130828" has been deprecated`
`typings WARN deprecated 6/2/2016, 4:13:32 PM: "registry:dt/core-js#0.0.0+20160317120654" has been deprecated`
`typings WARN deprecated 6/22/2016, 12:42:55 AM: "registry:dt/jasmine#2.2.0+20160505161446" has been deprecated`
`typings WARN deprecated 7/9/2016, 1:40:37 PM: "registry:dt/node#6.0.0+20160514165920" has been deprecated`
`typings WARN deprecated 5/23/2016, 5:55:35 AM: "registry:dt/webpack#1.12.9+20160321060707" has been deprecated`
...
`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:`
`npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12`

**Comment by olastor** [comment]
Strange ....

Changing line 3 `src/app/user/user.service.ts` from

`import { Observable } from 'rxjs/rx';`

to

`import { Observable } from 'rxjs/Rx';`

made it work! Maybe me using a different version of the module, nodejs or angular is causing this??

**Comment by binarious** [comment]
Nicely spotted
